### PR TITLE
Fix GHC 9 compatibility

### PR DESCRIPTION
**Pull request by mithrandi**

### CODE REVIEW

**Comment by jneira** [comment]
@lspitzner haskell-language-server support for ghc.9.0.1 is blocked on this, @lspitzner any chance to see this merged? thanks!

**Comment by tfausak** [comment]
This looks good to me! Unfortunately I'm not a maintainer of this repository, so I may end up publishing this as a fork. Or if you want to publish this, Tristan, that would work too.

**Comment by jneira** [comment]
maybe it would be time to publish the fork @tfausak?

**Comment by lspitzner** [comment]
I will release a new version with support for ghc-9 today. Sorry for the delay.

**Comment by jneira** [comment]
@lspitzner many thanks for find some time to take care and dont worry

any chance to consider add some other maintainer to the project and hackage?

**Comment by lspitzner** [comment]
I just uploaded https://hackage.haskell.org/package/czipwith-1.0.1.4. I was testing my package-testing scripts so I stupidly ignored this PR and pushed my own commits for ghc-9 support. Nonetheless, thank you @mithrandi for your PR!

@jneira the other brittany-maintainers also have push-rights on hackage, but I am fine to add more if it is useful for the future. Who is volunteering? I probably need the hackage-username to add.

**Comment by tfausak** [comment]
Oh, I didn't realize I was a package maintainer of czipwith on Hackage. Sorry!

**Pull request closed without merging**
